/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wbs_2103.GUI;
import javax.swing.JOptionPane;
import wbs_2103.Client;

/**
 *
 * @author Nhel Hernadez
 */
public class AdminViewClientReq extends javax.swing.JFrame {
    private static Client client = new Client();
    private static String username, location, contactNumber, status;
    private static int clientID;

    /**
     * Creates new form AdminViewClientReq
     */
    public AdminViewClientReq(Client client) {
        initComponents();
        this.clientID = clientID;
        this.username = username;
        this.location = location;
        this.contactNumber = contactNumber;
        this.status = status;
        this.client = client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backtoLogin = new javax.swing.JButton();
        confirmRequest = new javax.swing.JButton();
        acceptComp = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        request = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaintArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backtoLogin.setBackground(new java.awt.Color(204, 255, 255));
        backtoLogin.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        backtoLogin.setText("BACK");
        backtoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(backtoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 393, 100, 40));

        confirmRequest.setBackground(new java.awt.Color(51, 204, 255));
        confirmRequest.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        confirmRequest.setForeground(new java.awt.Color(255, 255, 255));
        confirmRequest.setText("Confirm Request");
        confirmRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRequestActionPerformed(evt);
            }
        });
        getContentPane().add(confirmRequest, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 149, 30));

        acceptComp.setBackground(new java.awt.Color(51, 204, 255));
        acceptComp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        acceptComp.setForeground(new java.awt.Color(255, 255, 255));
        acceptComp.setText("Accept Complaint");
        acceptComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptCompActionPerformed(evt);
            }
        });
        getContentPane().add(acceptComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 164, 30));

        request.setColumns(20);
        request.setRows(5);
        jScrollPane2.setViewportView(request);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 240, 170));

        complaintArea.setColumns(20);
        complaintArea.setRows(5);
        jScrollPane1.setViewportView(complaintArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, 170));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 70));

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 102));
        jLabel3.setText("AQUABILL");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptCompActionPerformed
        // TODO add your handling code here:
         try {
            
            if (client == null){
                JOptionPane.showMessageDialog(this, "No client object passed.");
                return;
                
            }
            
            client.saveComplaint(client.getclientID(), client.getComplaint());
            complaintArea.setText("");
            JOptionPane.showMessageDialog(this, "Your complaint has been submitted successfully!");
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_acceptCompActionPerformed

    private void confirmRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRequestActionPerformed
        // TODO add your handling code here:
          client.updateInfo(
                client.getcUsername(), 
                client.getcontactNumber(), 
                client.getlocation(), 
                client.getclientStatus(), 
                client.getclientID());
    }//GEN-LAST:event_confirmRequestActionPerformed

    private void backtoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoLoginActionPerformed
        // TODO add your handling code here:
         AdminUI adminui = new AdminUI();
            adminui.setVisible(true);
            dispose();
    }//GEN-LAST:event_backtoLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewClientReq(client).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptComp;
    private javax.swing.JButton backtoLogin;
    protected javax.swing.JTextArea complaintArea;
    private javax.swing.JButton confirmRequest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    protected javax.swing.JTextArea request;
    // End of variables declaration//GEN-END:variables
}
