/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wbs_2103.GUI;
import wbs_2103.Client;

/**
 *
 * @author Rica Mae
 */
public class AdminViewClientReq extends javax.swing.JFrame {
    private static Client client = new Client();
    private static String username, location, contactNumber, status;
    private static int clientID;
    /**
     * Creates new form AdminViewClientReq
     */
    public AdminViewClientReq(Client client) {
        initComponents();
        this.clientID = clientID;
        this.username = username;
        this.location = location;
        this.contactNumber = contactNumber;
        this.status = status;
        this.client = client;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        confirmRequestButton = new javax.swing.JToggleButton();
        acceptCompButton = new javax.swing.JToggleButton();
        backtoLoginButton = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        requestTextArea = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        complaintTextArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        confirmRequestButton.setBackground(new java.awt.Color(102, 204, 255));
        confirmRequestButton.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        confirmRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        confirmRequestButton.setText("CONFIRM REQUEST");
        confirmRequestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmRequestButtonActionPerformed(evt);
            }
        });
        getContentPane().add(confirmRequestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        acceptCompButton.setBackground(new java.awt.Color(102, 204, 255));
        acceptCompButton.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        acceptCompButton.setForeground(new java.awt.Color(255, 255, 255));
        acceptCompButton.setText("ACCEPT COMPLAINT");
        acceptCompButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptCompButtonActionPerformed(evt);
            }
        });
        getContentPane().add(acceptCompButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, -1, -1));

        backtoLoginButton.setBackground(new java.awt.Color(204, 255, 255));
        backtoLoginButton.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        backtoLoginButton.setText("BACK");
        backtoLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backtoLoginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backtoLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 410, -1, -1));

        requestTextArea.setColumns(20);
        requestTextArea.setRows(5);
        jScrollPane2.setViewportView(requestTextArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 320, 210));

        complaintTextArea.setColumns(20);
        complaintTextArea.setRows(5);
        jScrollPane1.setViewportView(complaintTextArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 340, 210));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Serif", 1, 33)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 153));
        jLabel1.setText("CLIENT REQUESTS/ COMPLAINTS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 610, 32));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nhel Hernadez\\Documents\\wbs_2103\\src\\wbs_2103\\GUI\\icons\\water-tap (2) (1).png")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 120, 50));

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("AQUABILL");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 110, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Nhel Hernadez\\Documents\\wbs_2103\\src\\wbs_2103\\GUI\\icons\\website design (1).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmRequestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmRequestButtonActionPerformed
        // TODO add your handling code here:
        
        client.updateInfo(
                client.getcUsername(), 
                client.getcontactNumber(), 
                client.getlocation(), 
                client.getclientStatus(), 
                client.getclientID());
    }//GEN-LAST:event_confirmRequestButtonActionPerformed

    private void backtoLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backtoLoginButtonActionPerformed
        // TODO add your handling code here:
        AdminUI adminui = new AdminUI();
            adminui.setVisible(true);
            dispose();
    }//GEN-LAST:event_backtoLoginButtonActionPerformed

    private void acceptCompButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptCompButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acceptCompButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewClientReq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewClientReq(client).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton acceptCompButton;
    private javax.swing.JToggleButton backtoLoginButton;
    private javax.swing.JTextArea complaintTextArea;
    private javax.swing.JToggleButton confirmRequestButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea requestTextArea;
    // End of variables declaration//GEN-END:variables
}
