/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package wbs_2103.GUI2;
import java.awt.Component;
import wbs_2103.Client;
import wbs_2103.Admin;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import wbs_2103.Control_Connector.DBConnect;
import wbs_2103.SharedData;
import java.sql.SQLException;
import java.time.LocalDate;
import wbs_2103.ClientState;



/**
 *
 * @author Rica Mae
 */
public class AdminUI extends javax.swing.JFrame {
    private static Client client = new Client();
    Admin admin = new Admin();
    private Connection connect;
    private Component rootPane;

    /**
     * Creates new form AdminUI
     */
    public AdminUI() {
        initComponents();
        admin.retrieveClientInfo();
        DBConnect dbconnect = new DBConnect();
        this.connect = dbconnect.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        clientTab = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        complaintLabel = new javax.swing.JLabel();
        refreshButton = new javax.swing.JButton();
        ackButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        monitorTable = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        collectLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(0, 153, 153));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("AQUABILL");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, 35));

        logoutButton.setText("LOG OUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });
        jPanel5.add(logoutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 476, -1, -1));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("ADMIN");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 150, 35));
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 120, 120));

        jLabel6.setText("jLabel6");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, -1));
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 180, 160));

        clientTab.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                clientTabStateChanged(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        complaintLabel.setBackground(new java.awt.Color(153, 153, 153));
        complaintLabel.setText("CLIENT COMPLAINT (DISPLAY) ");
        jPanel3.add(complaintLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 340, 130));

        refreshButton.setText("REFRESH");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel3.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 345, -1, -1));

        ackButton.setText("ACKNOWLEGE");
        ackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ackButtonActionPerformed(evt);
            }
        });
        jPanel3.add(ackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 345, 117, -1));

        jLabel11.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 0, 153));
        jLabel11.setText("VIEW CLIENT COMPLAINT");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, 35));

        jLabel4.setText("jLabel4");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 570, 470));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 570, 130));

        clientTab.addTab("VIEW COMPLAINT", jPanel3);

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        monitorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CLIENT ID", "METER ID", "AMOUNT", "PAID METER", "DATE", "STATUS"
            }
        ));
        jScrollPane2.setViewportView(monitorTable);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 103, 510, 410));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 0, 153));
        jLabel12.setText("VIEW CLIENT METER USAGE");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 19, 549, 35));

        jLabel5.setText("jLabel5");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 390));

        jLabel9.setText("jLabel9");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 386, 570, 190));

        clientTab.addTab("MONITOR CLIENT", jPanel6);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        collectLabel.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        collectLabel.setForeground(new java.awt.Color(0, 0, 153));
        collectLabel.setText("collection");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(collectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addComponent(collectLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        clientTab.addTab("COLLECTION", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientTab))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(clientTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        // hala ako gumawa ng exit button ha - nhel
        SharedData.adminID = 0;
        ClientState.verifiedID = -1;
        ClientState.isVerified = false;
        
        AdminSignIn adminsn = new AdminSignIn();
            adminsn.setVisible(true);
            dispose();
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void ackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ackButtonActionPerformed
        // TODO add your handling code here:
        try {
            int adminID = SharedData.adminID;
            if (adminID == 0) {
                JOptionPane.showMessageDialog(this, "Please log in to acknowledge complaint!");
                return;
            }
            
            String labelText = complaintLabel.getText();
            if (labelText.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No complaint to acknowledge!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }


            String clientIDText = labelText.split("Client ID: ")[1].split(" \\|")[0];
            int clientID = Integer.parseInt(clientIDText);


            admin.acknowledgeComplaint(clientID);

            complaintLabel.setText("");
            JOptionPane.showMessageDialog(this, "Complaint acknowledged successfully!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ackButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        try {
            int adminID = SharedData.adminID;
            if (adminID == 0) {
                JOptionPane.showMessageDialog(this, "Please log in to refresh complaint!");
                return;
            }

            String[] data = admin.fetchUnacknowledgedComplaint();

            complaintLabel.setText("Client ID: " + data[0] + " | Complaint: " + data[1]);
        } catch (Exception e) {
            complaintLabel.setText("");
            JOptionPane.showMessageDialog(this, e.getMessage(), "Information", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void clientTabStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_clientTabStateChanged
        // TODO add your handling code here:
        try {
            int adminID = SharedData.adminID;
            if (adminID == 0) {
                JOptionPane.showMessageDialog(this, "Please log in first!");
                return;
            }
            monitorClient();
            collection();

        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_clientTabStateChanged

    /**
     * @param args the command line arguments
     */
    
    public void monitorClient(){
        int adminID = SharedData.adminID;
        if (adminID == 0) {
            JOptionPane.showMessageDialog(this, "Please log in to load history!");
            return;
        }
        ArrayList<String> clientInfo = admin.retrieveClientInfo();

        DefaultTableModel tableModel = (DefaultTableModel) monitorTable.getModel();
        for (String row : clientInfo) {
            String[] rowInfo = row.split(", ");
            tableModel.addRow(rowInfo);
        }
    }
    
    public void collection(){
                try {
            int adminID = SharedData.adminID;
            if (adminID == 0) {
                JOptionPane.showMessageDialog(this, "Please log in to view collection!");
                return;
            }
          double totalPayments = admin.getTotalPayments();
           collectLabel.setText("<html>As of: " + LocalDate.now() + "<br>Total Payments: " + totalPayments + "</html>");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ackButton;
    private javax.swing.JTabbedPane clientTab;
    private javax.swing.JLabel collectLabel;
    private javax.swing.JLabel complaintLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton logoutButton;
    private javax.swing.JTable monitorTable;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
